# Generated by Django 5.2.7 on 2025-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_1', '0003_apiauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('view_products', 'Can view product list and details'), ('add_products', 'Can add new products'), ('edit_products', 'Can update or delete products'), ('view_expensive_product', 'Can view the most expensive product'), ('view_datalake', 'Can view Data Lake streams')], max_length=50),
        ),
    ]
