# Generated by Django 5.2.7 on 2025-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_1', '0005_alter_userpermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('view_products', 'Can view product list and details'), ('add_products', 'Can add new products'), ('edit_products', 'Can update or delete products'), ('view_expensive_product', 'Can view the most expensive product'), ('view_datalake', 'Can view Data Lake streams'), ('view_metrics', 'Can view aggregated metrics'), ('search_datalake', 'Can perform full-text search on Data Lake'), ('trigger_ml_model', 'Can trigger ML model training'), ('repush_transaction', 'Can re-push a single transaction to Kafka'), ('repush_all_transactions', 'Can re-push all historical data to Kafka (DANGEROUS)')], max_length=50),
        ),
    ]
